### ISSUE TITLE
Prepare pyjokes for Europython 2015

### ISSUE THREAD

**Issue by borjaayerdi** [bennuttall/pyjokes#3]
http://www.europython-society.org/

**Comment by bennuttall** [comment]
Can we close this?

**Comment by alexsavio** [comment]
Is the testing done? :P

On Fri, 24 Jul 2015 15:23 Ben Nuttall <notifications@github.com> wrote:

> Can we close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bennuttall/pyjokes/issues/3#issuecomment-124519059>.
>
-- 

Sent from my phone, sorry for brevity or typos.

**Comment by bennuttall** [comment]
```python
assert status == "It seems to work"
```

Yep

**Comment by alexsavio** [comment]
Great! Close it then. :+1:
