### ISSUE TITLE
Cannot get joke

### ISSUE THREAD

**Issue by sfontana** [bennuttall/pyjokes#8]
https://github.com/bennuttall/pyjokes/blob/master/pyjokes/pyjokes.py#L5

The function is called `get_joke` but sometimes I don't get the joke.
It's also non-deterministic because if I use `get_joke`and the same joke is shown, after a couple of times I get it and then I never have the same problem with that specific joke.

**Comment by bennuttall** [comment]
Hmm. That's interesting. I can't reproduce the error on my machine.

Have you installed the `intelligence` package? Or was it improperly configured?
